import nomane from "../../assets/icone/personne.jpeg";
import nomane1 from "../../assets/day.webp";
import nomane2 from "../../assets/esperance.webp";
export const group = [
  { id: 1, photo: nomane, title: "groupe1", description: "histoire1" },
  { id: 2, photo: nomane, title: "groupe2", description: "histoire2" },
  { id: 3, photo: nomane, title: "groupe3", description: "histoire1" },
  { id: 4, photo: nomane, title: "groupe4", description: "histoire1" },
  { id: 5, photo: nomane, title: "groupe5", description: "histoire1" },
  { id: 6, photo: nomane, title: "groupe6", description: "histoire1" },
  { id: 7, photo: nomane, title: "groupe7", description: "histoire1" },
  { id: 8, photo: nomane, title: "groupe8", description: "histoire1" },
  { id: 9, photo: nomane, title: "groupe9", description: "histoire1" },
  { id: 10, photo: nomane, title: "groupe10", description: "histoire2" },
  { id: 11, photo: nomane, title: "groupe11", description: "histoire1" },
  { id: 12, photo: nomane, title: "groupe12", description: "histoire1" },
  { id: 13, photo: nomane, title: "groupe13", description: "histoire1" },
  { id: 14, photo: nomane, title: "groupe14", description: "histoire1" },
  { id: 15, photo: nomane, title: "groupe15", description: "histoire1" },
  { id: 16, photo: nomane, title: "groupe16", description: "histoire1" },
];

export const ami = [
  { id: 1, photo: nomane, title: "ami1" },
  { id: 2, photo: nomane, title: "ami2" },
  { id: 3, photo: nomane, title: "ami3" },
  { id: 4, photo: nomane, title: "ami4" },
  { id: 5, photo: nomane, title: "ami5" },
  { id: 6, photo: nomane, title: "ami6" },
  { id: 7, photo: nomane, title: "ami7" },
  { id: 8, photo: nomane, title: "ami8" },
  { id: 9, photo: nomane, title: "ami9" },
  { id: 10, photo: nomane, title: "ami10" },
  { id: 11, photo: nomane, title: "ami11" },
  { id: 12, photo: nomane, title: "ami12" },
  { id: 13, photo: nomane, title: "ami13" },
  { id: 14, photo: nomane, title: "ami14" },
  { id: 15, photo: nomane, title: "ami15" },
  { id: 16, photo: nomane, title: "ami16" },
];
export const person = [
  { id: 1, photo: nomane, title: "personne1", description: "bonjour dimitri" },
  { id: 2, photo: nomane1, title: "personne2", description: "bonjour dimitri" },
  { id: 3, photo: nomane, title: "personne3", description: "bonjour dimitri" },
  { id: 4, photo: nomane2, title: "personne4", description: "bonjour dimitri" },
  { id: 5, photo: nomane, title: "personne5", description: "bonjour dimitri" },
  { id: 6, photo: nomane1, title: "personne6", description: "bonjour dimitri" },
  { id: 7, photo: nomane, title: "personne7", description: "bonjour dimitri" },
  { id: 8, photo: nomane2, title: "personne8", description: "bonjour dimitri" },
  { id: 9, photo: nomane, title: "personne9", description: "bonjour dimitri" },
  {
    id: 10,
    photo: nomane,
    title: "personne10",
    description: "bonjour dimitri",
  },
  {
    id: 11,
    photo: nomane,
    title: "personne11",
    description: "bonjour dimitri",
  },
  {
    id: 12,
    photo: nomane,
    title: "personne12",
    description: "bonjour dimitri",
  },
  {
    id: 13,
    photo: nomane,
    title: "personne13",
    description: "bonjour dimitri",
  },
  {
    id: 14,
    photo: nomane,
    title: "personne14",
    description: "bonjour dimitri",
  },
  {
    id: 15,
    photo: nomane,
    title: "personne15",
    description: "bonjour dimitri",
  },
  {
    id: 16,
    photo: nomane,
    title: "personne16",
    description: "bonjour dimitri",
  },
];
export const personall = [
  { id: 1, photo: nomane, title: "personne1", description: "bonjour dimitri" },
  { id: 2, photo: nomane, title: "personne2", description: "bonjour dimitri" },
  { id: 3, photo: nomane, title: "personne3", description: "bonjour dimitri" },
  { id: 4, photo: nomane, title: "personne4", description: "bonjour dimitri" },
  { id: 5, photo: nomane, title: "personne5", description: "bonjour dimitri" },
  { id: 6, photo: nomane, title: "personne6", description: "bonjour dimitri" },
  { id: 7, photo: nomane, title: "personne7", description: "bonjour dimitri" },
  { id: 8, photo: nomane, title: "personne8", description: "bonjour dimitri" },
  { id: 9, photo: nomane, title: "personne9", description: "bonjour dimitri" },
  {
    id: 10,
    photo: nomane,
    title: "personne10",
    description: "bonjour dimitri",
  },
  {
    id: 11,
    photo: nomane,
    title: "personne11",
    description: "bonjour dimitri",
  },
  {
    id: 12,
    photo: nomane,
    title: "personne12",
    description: "bonjour dimitri",
  },
  {
    id: 13,
    photo: nomane,
    title: "personne13",
    description: "bonjour dimitri",
  },
  {
    id: 14,
    photo: nomane,
    title: "personne14",
    description: "bonjour dimitri",
  },
  {
    id: 15,
    photo: nomane,
    title: "personne15",
    description: "bonjour dimitri",
  },
  {
    id: 16,
    photo: nomane,
    title: "personne16",
    description: "bonjour dimitri",
  },
];
